#!/bin/bash

xsetroot -solid black &
xsetroot -cursor_name left_ptr &
#xmodmap .Xmodmap

if [ ! -f ~/.xbindkeysrc ]; then
    xbindkeys --defaults > ~/.xbindkeysrc &
fi
xbindkeys &

# Set X background image
#feh --bg-scale ~/.wallpaper.png &

#eval $(gnome-keyring-daemon --start)
#export GNOME_KEYRING_SOCKET
#export GNOME_KEYRING_PID
#
#exec ck-launch-session xmonad

if [ $(~/.local/bin/monitors_hash) == "ebea32402397374b0e05a967246de9ffae796d6c393fa98a157d38d4843080af" ]; then
    # linuxdojo lab
    #xrandr \
    #    --fb 10240x5040 \
    #    --output DP-1-1 --scale 1x1 --mode 2560x1600 --pos 0x0 \
    #    --output DP-3 --scale 1x1 --mode 2560x1440 --pos 2560x0 \
    #    --output eDP-1 --scale 0.5x0.5 --mode 3840x2160 --pos 2560x1440 \
    #    > /dev/null 2>&1

    xrandr \
        --output DP-1-1 --mode 2560x1600 --pos 0x0 \
        --output DP-3 --mode 2560x1440 --pos 2560x0 \
        --output eDP-1 --mode 1920x1200 --pos 2560x1440 \
        > /dev/null 2>&1


elif [ $(~/.local/bin/monitors_hash) == "9c603045c6cda87214106f8f84483cf99fb730738ac0f4de7ef4a4a284e19dd8" ]; then
    # phsl
#    xrandr \
#        --output DP-3 --scale 2x2 --mode 2560x1080 --pos 0x0 \
#        --output DP-1 --scale 2x2 --mode 1920x1080 --pos 5120x0 \
#        --output eDP-1 --scale 1x1 --mode 3840x2160 --pos 0x2160 \
#        > /dev/null 2>&1
    xrandr \
        --output DP-1 --scale 1x1 --mode 1920x1080 --pos 2560x0 \
        --output DP-3 --scale 1x1 --mode 2560x1080 --pos 0x0 \
        --output eDP-1 --scale 0.5x0.5 --mode 3840x2160 --pos 0x1080 \
        > /dev/null 2>&1

fi

date +"%s" > ~/.xinitrc_lastupdate

